LOAD DATA
INFILE 'HMS_DOC_AVAIL_DATA_MD.csv'
INTO TABLE HMS_DOCTOR_AVAILABILITY_STG_MD
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(AVAILABILITY_ID, DOCTOR_ID, DOCTOR_DEPARTMENT, AVAILABILITY_DAY, START_TIME, END_TIME)
