LOAD DATA
INFILE 'HMS_EMP_PHONE_DATA_NM.csv'
INTO TABLE HMS_EMPLOYEE_PHONE_MST_STG_NM
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(PHONE_RECORD_ID, EMPLOYEE_ID, PHONE1, PHONE2)
