OPTIONS (SKIP=1)
LOAD DATA
INFILE 'HMS_DOC_AVAIL_DATA_SH.csv'
INTO TABLE HMS_DOCTOR_AVAILABILITY_STG_SH
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    STG_ID EXPRESSION "HMS_DOC_AVAIL_STG_SEQ_SH.NEXTVAL",
    BATCH_ID CONSTANT 'BATCH_SH',
    CREATED_BY CONSTANT 1021027,
    CREATION_DATE SYSDATE,
    LAST_UPDATED_BY CONSTANT 1021027,
    LAST_UPDATE_DATE SYSDATE,
AVAILABILITY_ID, DOCTOR_ID, DOCTOR_DEPARTMENT, AVAILABILITY_DAY, START_TIME, END_TIME)
