OPTIONS (SKIP=1)
LOAD DATA
INFILE 'HMS_EMP_PHONE_DATA_SH.csv'
INTO TABLE HMS_EMPLOYEE_PHONE_MST_STG_SH
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    STG_ID "HMS_EMP_PHONE_STG_SEQ_SH.NEXTVAL",
    BATCH_ID CONSTANT 'BATCH_SH',
    CREATED_BY CONSTANT 1021027,
    CREATION_DATE SYSDATE,
    LAST_UPDATED_BY CONSTANT 1021027,
    LAST_UPDATE_DATE SYSDATE,
PHONE_RECORD_ID, EMPLOYEE_ID, PHONE1, PHONE2)
