OPTIONS (SKIP=1)
LOAD DATA
INFILE 'HMS_DOC_AVAIL_DATA_CH.csv'
INTO TABLE HMS_DOCTOR_AVAILABILITY_STG_CH
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    STG_ID EXPRESSION "HMS_DOC_AVAIL_STG_SEQ_CH.NEXTVAL",
    BATCH_ID CONSTANT 'BATCH_CH',
    CREATED_BY CONSTANT 1021034,
    CREATION_DATE SYSDATE,
    LAST_UPDATED_BY CONSTANT 1021034,
    LAST_UPDATE_DATE SYSDATE,
AVAILABILITY_ID, DOCTOR_ID, DOCTOR_DEPARTMENT, AVAILABILITY_DAY, START_TIME, END_TIME)
