OPTIONS (SKIP=1)
LOAD DATA
INFILE 'HMS_EMP_PHONE_DATA_CH.csv'
INTO TABLE HMS_EMPLOYEE_PHONE_MST_STG_CH
APPEND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    STG_ID "HMS_EMP_PHONE_STG_SEQ_CH.NEXTVAL",
    BATCH_ID CONSTANT 'BATCH_CH',
    CREATED_BY CONSTANT 1021034,
    CREATION_DATE SYSDATE,
    LAST_UPDATED_BY CONSTANT 1021034,
    LAST_UPDATE_DATE SYSDATE,
PHONE_RECORD_ID, EMPLOYEE_ID, PHONE1, PHONE2)
